name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Install Laravel
      run: composer create-project laravel/laravel -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Dependencies
      run: cd laravel && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: cd laravel && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Install package
      run: cd laravel && composer config repositories.laravolt path ./.. && composer require ramaid/laravolt:dev-main && php artisan laravolt:install
    - name: Install package js
      run: cd laravel && npm install tailwindcss && npm run build
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd laravel && vendor/bin/phpunit
